### PR TITLE
Use new action to create issues in DEP workflow

### PR DESCRIPTION
**Pull request by td928**
Address #134 

After some trial and error finally was able to get it to work like we used to. See #137 for the issue created with the new workflow and [this action run](https://github.com/NYCPlanning/ceqr-app-data/actions/runs/3652664035/jobs/6171306680) to see the details. 

The main difference with [this new action](https://github.com/JasonEtco/create-an-issue) is that it requires the use of a issue template. So it required me to migrate most of the content from the workflow file to the issue template `..github/ISSUE_TEMPLATE/dep-monthly.md` for it to work as it used to.

### CODE REVIEW

**Comment by mbh329** [comment]
@td928 Are you planning to update the other workflows in this PR?

**Comment by mbh329** [comment]
It looks as though the other workflows amanda tried running also use `nashmaniac/create-issue-action@v1.1 `[see here](https://github.com/NYCPlanning/ceqr-app-data/actions/runs/3549817937)

**Comment by td928** [comment]
> It looks as though the other workflows amanda tried running also use `nashmaniac/create-issue-action@v1.1 `[see here](https://github.com/NYCPlanning/ceqr-app-data/actions/runs/3549817937)

thanks for flagging. Yeah didn't see those so I will take a look at switching those over as well

**Comment by td928** [comment]
Hey @mbh329 l restore this branch to only fix the DEP monthly workflow. Please let me know if this looks good and we can discuss how to fix the other ones. Thanks!

**Review by mbh329 — APPROVED** [review]
This looks good to me! I think we should double check with James, Omar, and Leo if this works as expected for them as they know the process the best

**Review by AmandaDoyle — APPROVED** [review]
Approving on the condition that the following is true based on my read and understanding of the new GitHub action.
On the first of very month an issue will be opened based on this template, kicking off the data update process, and the once it's complete commenting in existing issue that the job is done?
If that is true, please merge in.  If that is false, let's chat.

**Comment by td928** [comment]
> this action run

The order of operation is a data update would get kicked off 1st of every month and once the new data pull finished a issue would get created to notify the team for review but yes otherwise the outcome is the same as what you are describing @AmandaDoyle

**Pull request merged**
